spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/myproject?allowPublicKeyRetrieval=true&ssl=false&createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: postgres
    password: root

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  sql:
    init:
      mode: always
      encoding: UTF-8

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    open-in-view: false
    properties:
      hibernate:
#        generate_statistics: true
#        use_sql_comments: true
#        format_sql: true
##        show SQL statements only if needed!
#        show_sql: true
#        type: trace

  web:
    resources:
      cache:
        cachecontrol:
          max-age: 365d
      chain:
        strategy:
          content:
            enabled: true
            paths: /**

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_OAUTH2_SECRET}

  #Cloudinary Properties
cloudinary:
  api-key: 579953547744991
  api-secret: ${CLOUDINARY_API_SECRET}
  cloud-name: trippictures

  #Loggers
logging:
  level:
    org.springframework: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: Trace
#    sql: debug
server:
  port: 8080
